1654494911801352037 1095947940
1654494912131395088 316007895
1654494912828191797 419984685
1654494913217459801 385054087
1654494916830627497 116653379
1654494918138836486 239515636
1654494921003391458 1910528491
1654494922414434000 290850970
1654494923995263957 1580465046
1654494925643486079 136892961
1654494927429712330 1785917545
1654494927720003637 289909264
1654494928293921761 573405813
1654494929108067789 813604282
1654494932419015413 1626106783
1654494932917611246 202508436
1654494935836288053 617910210
1654494938635904278 814850673
1654494941122847261 1693159339
1654494943925816070 319165926
1654494945635013153 1502141687
1654494947730172964 202093868
1654494948197906849 466834068
1654494950899097314 1665719684
1654494952138875270 524246413
1654494952998407444 800431292
1654494953323382106 324524523
1654494953828169514 335544322
1654494955421001702 707806318
1654494958528538169 1398792699
1654494958831598382 302297369
1654494961214818981 914582494
1654494964425994053 2131456259
1654494966719727042 1927045170
1654494968130043844 1409895640
1654494968429044070 298691250
1654494970522084633 324246430
1654494971707787127 587822445
1654494973519550499 588776563
1654494974125278346 605454671
1654494974528612356 326812098
1654494977018534287 605627296
1654494977634023647 535857973
1654494981012634261 3378231799
1654494983817202305 1301034657
1654494984394003122 575950231
1654494986816729641 694522057
1654494990725122805 924907286
1654494993946558942 1722896409
1654494996029168403 2082188952
1654494997797733924 278967606
1654494999231282799 506545613
1654495001095385846 775834034
1654495004621742132 3526056281
1654495006627775886 316065337
1654495008604358373 481024927
1654495010732367936 713572453
1654495012630774188 227268935
1654495014808251101 911949133
1654495016306950510 1498047897
1654495017818961010 216991798
1654495020194358832 596573587
1654495021838701864 422688977
1654495023833076352 826550105
1654495024930050998 1024750261
1654495026424076151 424728465
1654495028234792709 1231664552
1654495031193370249 1600391608
1654495032902109230 969380573
1654495033937179191 627358828
1654495034393431303 455821506
1654495035025643536 427758876
1654495036936423261 823808898
1654495038502721083 493428555
1654495039130111710 505691648
1654495040203781367 202230560
1654495051303737919 7977487245
1654495051799743710 283124862
1654495052108053944 307885188
1654495055295280000 2086002096
Exception in thread 27:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "app.py", line 48, in _kubernetes_job
    _write_work(**kwargs)
  File "app.py", line 67, in _write_work
    simple_http_client_post.perform(gibberish_content)
  File "/app/models/simple_http_log_client.py", line 12, in perform
    return self._simple_requests_scenario(body_json_content)
  File "/app/models/simple_http_log_client.py", line 17, in _simple_requests_scenario
    return self.session.post(f"{self.api_url}/db", json=body_json_content)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

1654495056025163870 609909125
1654495057631071659 233337788
1654495058220218857 588362203
1654495059020925630 800151017
1654495060710295336 1688717820
1654495062523554296 220174215
1654495065192756543 1575869744
1654495065740338327 416907409
1654495068008642660 594509706
1654495068619402868 610521585
1654495069221608936 407375681
1654495070823571893 1601429267
1654495072901686562 494812443
1654495088517419623 15511612846
1654495090628247352 1696757174
1654495091603679510 699437953
1654495092228852839 604257452
1654495092708728504 479312122
1654495093418952935 709675065
1654495099132361169 997711974
1654495100721808675 291111647
1654495101098734263 171745888
1654495103732893961 438804979
1654495105216904378 1294485716
1654495110333424222 1623415046
1654495111714016929 411906249
1654495113120609799 489772136
1654495115917976004 692816030
1654495118239112797 599585153
1654495120203188679 488291694
1654495121298841550 785334892
1654495124398981356 484198311
1654495125811429993 588018996
1654495127912180915 816149131
1654495130618906770 1393766065
1654495131434779229 815519938
1654495133509610401 1276525319
1654495136826678742 1617493060
1654495137898165670 298572708
1654495138236098304 311610786
1654495139498660628 398874163
1654495141098214157 468042198
1654495142732827743 1495224362
1654495146137695581 716187593
1654495146806056126 667837441
1654495148427427376 526184964
1654495150303910580 570133147
1654495152627841824 1709927334
1654495154201818329 1289774110
1654495154501471803 299377096
1654495156807759046 579765367
1654495158208734983 499811765
1654495160015756038 1806500588
1654495160705165084 688838163
1654495161321354136 521431079
1654495164020183297 2698277739
1654495164831624161 811134714
1654495168722304995 1517322582
1654495169132373582 296736301
1654495170914593591 577338687
1654495171703120101 475743908
1654495174594540205 279665201
1654495183421149076 7591711206
1654495183621467634 199852966
1654495187118892639 3325906993
1654495191416755254 1891340902
1654495192892589867 1475302753
1654495193233047617 340068735
1654495194898995781 899806264
1654495199399988622 501780290
1654495203300414247 890924301
1654495204415195013 215553054
1654495207399284619 1898640362
